server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  security:
    user:
      name: netflix
      password: eureka